### ISSUE TITLE
Questions regarding Events and Orbit Controls

### ISSUE THREAD

**Issue by moethu** [g3n/engine#138]
Hi, two questions regarding the latest changes to g3n:
- Events before and after rendering have been removed, am I supposed to use the add them using the new run method ```a.Run(func(renderer *renderer.Renderer, deltaTime time.Duration) { before / render / after }``` ?
- Orbit controls & mouse events changed quite a bit, before I was injecting MouseEvents. Should I simply implement my own orbit controls and use them instead?
Thanks

**Comment by danaugrs** [comment]
Hi @moethu, users now have full control over the application loop so you can call functions directly from there. No need to use events for that anymore 😄

The `OrbitControl` still listens to events so injecting them should still work!

This change that you noticed was pretty big as it involved work since the beginning of the year to add WebAssembly support. Normally things are more stable. Also, I recently added support for go modules (https://github.com/g3n/engine/commit/bb06976c0b256516a3219c85cab68a554a5872ff) which I highly recommend you do for [your project](https://github.com/moethu/webg3n) as well. To do that see [here](https://blog.golang.org/using-go-modules) and [here](https://blog.golang.org/migrating-to-go-modules). That way your project can depend on a specific version of g3n and it won't break when changes to g3n are made. You can then always upgrade to the latest g3n version whenever you like.

Additionally, I'm currently working on improving the camera API and those changes should hopefully be ready in a few days. Let me know if you have any other questions!

**Comment by moethu** [comment]
thanks @danaugrs, the changes are great, they make a lot of things much easier on my end.
