### ISSUE TITLE
demos/hellog3n/main.go return error on build

### ISSUE THREAD

**Issue by EParisot** [g3n/engine#145]
Hi,
When using "go build" command from my project folder (just trying the demo from demos/hellog3n/main.go), I got the following error message:

"cannot load github.com/g3n/engine/app: cannot find module providing package github.com/g3n/engine/app"

Any help ?

**Comment by EParisot** [comment]
Ok it works after the "go get" installation process...
Can you just update the release ?

**Comment by cloudfstrife** [comment]
i get same error ,  release v0.1.0 package do not include 'app' folder 
when go version >= 1.11 and use go module manager dependencies . go module fetch the latest release package, so cannot found app sub folder.
so next release include the newest code struct will solution this problem.

**Comment by AdamLenda** [comment]
I suspect this is the worst solution, but here's what I did to get things playing nicely with `go mod`

1) Forked repo to https://github.com/AdamLenda/engine
2) Replaced all imports in the source that were `github.com/g3n/engine/...` with `github.com/adamlenda/engine/...`
3) Created a v0.1.2 tag
4) created a v0.1.2 release

Since i did all of that in a fork, it won't impact original repo.

It did allow me to get the hello g3n example to build and run though.

Feel free to use what I've done.

All you need to do is modify the `hello g3n` example to use `adamlenda` in place of `g3n` in the imports

**Comment by Buhrietoe** [comment]
I agree a new tag should be created. The workaround if you're using go modules, is just update your dependancy to the latest commit on master:
go get github.com/g3n/engine@master

**Comment by mikechip** [comment]
> I agree a new tag should be created. The workaround if you're using go modules, is just update your dependancy to the latest commit on master:
> go get github.com/g3n/engine@master

Yes, it's the simplest solution.

**Comment by danaugrs** [comment]
This was fixed in [v0.2.0](https://github.com/g3n/engine/tree/v0.2.0). Sorry for the delay in responding.
