### ISSUE TITLE
Proper way to create new geometries?

### ISSUE THREAD

**Issue by superloach** [g3n/engine#158]
I was attempting to model a rhombic dodecahedron, but quickly realised that the existing code for creating geometries was somewhat convoluted. Am I missing something? I feel like there should be a simpler way to build a solid from a set of vertices.

**Comment by superloach** [comment]
I have succeeded in creating the shape I want:
```go
func NewRhodo(edge float32) *geometry.Geometry {
	geom := geometry.NewGeometry()
	vertices := math32.NewArrayF32(0, 16)

	c0 := edge * 3 * math32.Pow(2, 0.5) / 8
	c1 := c0 * 2

	v := make([]math32.ArrayF32, 14)
	v[0] = math32.ArrayF32{0.0, 0.0, c1}
	v[1] = math32.ArrayF32{0.0, 0.0, -c1}
	v[2] = math32.ArrayF32{c1, 0.0, 0.0}
	v[3] = math32.ArrayF32{-c1, 0.0, 0.0}
	v[4] = math32.ArrayF32{0.0, c1, 0.0}
	v[5] = math32.ArrayF32{0.0, -c1, 0.0}
	v[6] = math32.ArrayF32{c0, c0, c0}
	v[7] = math32.ArrayF32{c0, c0, -c0}
	v[8] = math32.ArrayF32{c0, -c0, c0}
	v[9] = math32.ArrayF32{c0, -c0, -c0}
	v[10] = math32.ArrayF32{-c0, c0, c0}
	v[11] = math32.ArrayF32{-c0, c0, -c0}
	v[12] = math32.ArrayF32{-c0, -c0, c0}
	v[13] = math32.ArrayF32{-c0, -c0, -c0}

	for _, n := range []int{
		6, 0, 2, 8, 0, 2, 6, 2, 4, 7, 2, 4, 6, 4, 0, 10, 4, 0, 9, 1, 2, 7, 1, 2,
		9, 2, 5, 8, 2, 5, 9, 5, 1, 13, 5, 1, 11, 1, 3, 13, 1, 3, 11, 3, 4, 10, 3, 4,
		11, 4, 1, 7, 4, 1, 12, 0, 3, 10, 0, 3, 12, 3, 5, 13, 3, 5, 12, 5, 0, 8, 5, 0,
	} {
		vertices.Append(v[n]...)
	}

	geom.AddVBO(gls.NewVBO(vertices).AddAttrib(gls.VertexPosition))

	return geom
}
```
I am aware of the issues with material sides here, and I intend to fix them.
However, at the moment this geometry doesn't appear to work with lighting at all, which is more concerning.

![2019-12-20-195350_1366x768_scrot](https://user-images.githubusercontent.com/30514424/71300409-839b9480-2362-11ea-98dd-de95e68c33c4.png)
(pictured: a rhombic dodecahedron inside a demo torus - light works on the torus, but not on the rhodo)

**Comment by aprice2704** [comment]
I am in a similar position, I have successfully made a mesh, which displays very nicely, but when not in wireframe mode I get a rather mottled effect rather than nice shading.
![image](https://user-images.githubusercontent.com/225169/72131367-da2c3b00-3330-11ea-8a99-9014b888c78e.png)
![image](https://user-images.githubusercontent.com/225169/72131403-f5974600-3330-11ea-9c6b-c695eb507837.png)
Any ideas appreciated :D

**Comment by danaugrs** [comment]
Hi @superloach and @aprice2704 - you need to create a VBO containing the normal for each vertex and add that VBO to the geometry. As a first order test to see that that works (since your models are convex) you can simply create a VBO with the same contents of your vertex VBO except that each Vector3 should be normalized.
```go
geom.AddVBO(gls.NewVBO(normalizedVertices).AddAttrib(gls.VertexNormal))
```

**Comment by Strosel** [comment]
Im having similar issues when trying to render an STL. I tried @danaugrs suggestion of adding the normalized vectors with no success. Is there any other known fix for this?

**Comment by danaugrs** [comment]
@Strosel if you post your code I can help debug it
