### ISSUE TITLE
Windows: high GPU usage error

### ISSUE THREAD

**Issue by SeanTolstoyevski** [g3n/engine#193]
Hi,

When I compile the **demo in Readme**, GPU usage increases to **52% or more**.
I do not do anything.

When I examined the codes, I couldn't find any **loop** that could cause this.

I am using 64 bit go.
Version 1.14
Windows 2004, 64-bit
AMD graphics card.

All works with g3n have the same problem.

I will use g3n only for **GUI and audio**. In this case, I do not need any physical.
I will not do any **visual rendering**.

**Comment by danaugrs** [comment]
Hi! That's odd.
Did you try removing the torus from the scene? What is the GPU usage then?
Also, how are you measuring GPU usage?

**Comment by SeanTolstoyevski** [comment]
Thanks for your answer.

> Did you try removing the torus from the scene?

I don't know how to do this. Would you say?

> Also, how are you measuring GPU usage?

The GPU usage percentages of applications are shown in Task Manager.

To use the GPU at a high percentage, an action **like rendering** is required. But there is no such process here.
Even the example that says **'Hello world'** causes high GPU usage.

**Comment by danaugrs** [comment]
Sure! To remove the torus you can comment out the line `scene.Add(mesh)`.

**There is** rendering in the "hello world" example from the readme, otherwise you wouldn't see anything. Rendering is triggered by `renderer.Render(scene, cam)`. Even pure UI applications require rendering.

The amount of computation necessary to render the torus and button in the "hello world" example is small though, so it's weird that you are getting high GPU usage.

What AMD graphics card are you using?

**Comment by SeanTolstoyevski** [comment]
Card:
AMD radeon m430 (leptop)

I made the changes. Now my GPU usage is 70-85%. And the CPU is 40-50%. Terrible numbers.

No program uses that much GPU.
Sometimes I run AI projects like LC0.

and new code:
```go
package main

import (
	"github.com/g3n/engine/app"
	"github.com/g3n/engine/gls"
	"github.com/g3n/engine/gui"
	"github.com/g3n/engine/light"
	"github.com/g3n/engine/material"
	"github.com/g3n/engine/math32"
	"github.com/g3n/engine/renderer"
	"github.com/g3n/engine/window"
	"time"
)

func main() {

	// Create application and scene
	a := app.App()

	onResize := func(evname string, ev interface{}) {
		// Get framebuffer size and update viewport accordingly
		width, height := a.GetSize()
		a.Gls().Viewport(0, 0, int32(width), int32(height))
		// Update the camera's aspect ratio
	}
	a.Subscribe(window.OnWindowSize, onResize)
	onResize("", nil)

	// Create a blue torus and add it to the scene
	// geom := geometry.NewTorus(1, .4, 12, 32, math32.Pi*2)
	mat := material.NewStandard(math32.NewColor("DarkBlue"))
	// mesh := graphic.NewMesh(geom, mat)
	// scene.Add(mesh)

	// Create and add a button to the scene
	btn := gui.NewButton("Make Red")
	btn.SetPosition(100, 40)
	btn.SetSize(40, 40)
	btn.Subscribe(gui.OnClick, func(name string, ev interface{}) {
		mat.SetColor(math32.NewColor("DarkRed"))
	})
	//scene.Add(btn)

	// Create and add lights to the scene
	//scene.Add(light.NewAmbient(&math32.Color{1.0, 1.0, 1.0}, 0.8))
	pointLight := light.NewPoint(&math32.Color{1, 1, 1}, 5.0)
	pointLight.SetPosition(1, 0, 2)
	// scene.Add(pointLight)

	// Create and add an axis helper to the scene
	// scene.Add(helper.NewAxes(0.5))

	// Set background color to gray
	a.Gls().ClearColor(0.5, 0.5, 0.5, 1.0)

	// Run the application
	a.Run(func(renderer *renderer.Renderer, deltaTime time.Duration) {
		a.Gls().Clear(gls.DEPTH_BUFFER_BIT | gls.STENCIL_BUFFER_BIT | gls.COLOR_BUFFER_BIT)
		// renderer.Render(scene, cam)
	})
}


```

**Comment by MrWaggel** [comment]
I looked up that GPU, and it is unfortunately on the (very) low performance side of the spectrum, and mostly shipped in laptops with CPU's which shares the same story.

I see you want to create a flat, two dimensional GUI application, and as much as I love this project, a game engine isn't the right fit for your idea, know that GUI rendering is also 'visual' rendering.

Check out [awesome-go](https://github.com/avelino/awesome-go), you'll find your two more suitable packages for GUI and sound there. But since you are worried about performance I'll have to tell you that pretty much most (all?) of the GUI libraries in go uses cgo to wrap c libraries (like [gl-fw](https://github.com/go-gl/gl) used here in g3n), which in plain means mapping between a non garbage collected language c, and our garbage collected language go. This causes some overhead and might a be part of the struggle for entry level hardware.

**Comment by 529124368** [comment]
@SeanTolstoyevski 
I also encountered 100% GPU usage today. I also just came into contact with this 3D library. I found that the reason is that the refresh rate limit is not set in the update. This setting is available in the official demo for reference. The keyword is frameRater. In my opinion, the GPU is also like the CPU. If you encounter an infinite loop without sleep, there will be 100% problems.
```golang
func (a *App) Update(rend *renderer.Renderer, deltaTime time.Duration) {

	// Start measuring this frame
	a.frameRater.Start()

	// Clear the color, depth, and stencil buffers
	a.Gls().Clear(gls.COLOR_BUFFER_BIT | gls.DEPTH_BUFFER_BIT | gls.STENCIL_BUFFER_BIT) // TODO maybe do inside renderer, and allow customization

	// Update the current running demo if any
	if a.currentDemo != nil {
		a.currentDemo.Update(a, deltaTime)
	}

	// Render scene
	err := rend.Render(a.scene, a.camera)
	if err != nil {
		panic(err)
	}

	// Update GUI timers
	gui.Manager().TimerManager.ProcessTimers()

	// Update statistics
	if a.stats.Update(time.Second) {
		if a.statsTable != nil {
			a.statsTable.Update(a.stats)
		}
	}

	// Update render stats
	if *oRenderStats {
		stats := a.Renderer().Stats()
		if stats.Panels > 0 {
			a.log.Debug("render stats:%+v", stats)
		}
	}

	// Control and update FPS
	a.frameRater.Wait()
	a.updateFPS()
}

**Comment by mrjrieke** [comment]
> I see you want to create a flat, two dimensional GUI application, and as much as I love this project, a game engine isn't the right fit for your idea, know that GUI rendering is also 'visual' rendering.
-- Sorry, but I beg to differ.  It depends on where he wants to take this.  This may be the perfect starting point for @SeanTolstoyevski and without knowing more I wouldn't want to drive him to another sdk that is limiting.
