### ISSUE TITLE
Sprite with alpha glitching against textured floor plane

### ISSUE THREAD

**Issue by harbdog** [g3n/engine#231]
I'm experiencing an issue where viewing a sprite, which has a texture image containing alpha, at certain angles has its alpha channel showing when against a textured background/floor.

G3N Version: `github.com/g3n/engine v0.1.1-0.20210127232258-6d0136f3444c` and `v0.1.1-0.20200214161420-db7282a2ba23` from G3N Demo project

![bad-transparency](https://user-images.githubusercontent.com/1300522/113492315-8e6d3080-94a4-11eb-8ac3-4443c11a592e.gif)

Here's a gist with the G3ND tests/model.go code to reproduce the problem:
Gist: https://gist.github.com/harbdog/6e32a467b45779126fe6a15cd007cd0a

**Comment by danaugrs** [comment]
Hi, and thanks for providing a GIF and reproduceable example!
This happens because both the sprite and the plane have a transparent material, so their render order is computed by comparing the distance between their centers with the camera.
You can manually modify the render order of the sprite to be drawn on top of the plane via `s1.SetRenderOrder(1)`.
Then it will always show up above the plane.

**Comment by harbdog** [comment]
Excellent thanks for the tip! Setting the floor plane render order to -1 also did the trick
