### ISSUE TITLE
Should loader.Decode() support .obj files without a corresponding material?

### ISSUE THREAD

**Issue by justinclift** [g3n/engine#29]
Asking because although the example files (eg gopher.obj, gopher.mtl) work fine, I have several .obj files without materials (generated by CAD programs).

Was kind of thinking to import the obj files using `loader.Decode()`, then manually create + apply a material to each imported one.

At the moment, `loader.Decode()` treats a missing material file as an error.  Am kind of thinking it might be useful to allow it to proceed instead, and pass (say) `nil` to `loader.DecodeReader()` which would skip attempting to parse the missing material too.

Can make a PR, which shouldn't suck too hard code wise. :wink:

Thoughts? :smile:

**Comment by justinclift** [comment]
As a data point, that does work.  eg updating `loader.Decode()` and `loader.DecodeReader()` to allow passing objects without material data, then manually applying material(s) afterwards.

**Comment by leonsal** [comment]
I think it is a good idea, but if the material file was not supplied and the obj file refers to a material an error should be generated. Another option, instead of generating a mesh without material, could be to use a default material, so the model would be visible in the scene after being loaded.

**Comment by justinclift** [comment]
Ahhhh, the default material approach seems really good.  That would also work for when the obj file references a material, but the mtl file (even if provided) doesn't include it.  (eg mismatching file pairs and similar)

I'll see if I can work up a decent PR to get this happening.  I'll need to step through the import code a bit more first, to grok it better.

**Comment by justinclift** [comment]
Meh, I probably won't get around to this after all.  Gotten kind of distracted by other, higher priority, stuff instead. :wink:

**Comment by danaugrs** [comment]
No problem, thanks for the involvement! 😄

**Comment by quillaja** [comment]
I had this problem today too. I was trying to load a generic "teapot" OBJ that doesn't have a material file, and the g3nview demo just stopped. I can't even "handle" the error by modifying the demo to ignore it, since the OBJ parsing just comes to a screeching halt.

I like the idea @leonsal suggested of providing a default material (which could later be changed in the user's code) if a corresponding .mtl file isn't found for the OBJ.

@danaugrs  If there's interest, I could probably implement this and submit a PR after I look at the relevant code in more detail.

**Comment by danaugrs** [comment]
@quillaja That would be great! Looking forward to that PR 😄

**Comment by quillaja** [comment]
Progress update: I looked through the relevant code, really just `loader/obj/obj.go` and got an understanding of what's going on. I've identified 2 semi-related issues with 'default' materials: (1) the code essentially assumes materials will be provided in `.mtl` (the issue we're setting out to solve), (2) the code ignores that OBJ does not require materials to be specified, via `usemtl`, for faces--geometry only OBJ is apparently allowed.

I got a basic kludge working, using the demo/g3nview program to test. (1) basically involves overwriting all the named materials in the OBJ file with a default. (2) is detecting when lists/dicts of materials are empty and using a default material instead of the usual material creation. Neither touches the actual parsing much, mostly the mesh creation.

Of course I still have to play with it more and clean and comment it.
Hopefully that makes some sense... it's past bedtime =)

**Comment by quillaja** [comment]
@justinclift If possible (assuming they aren't confidential, etc), could you send me one or two of your CAD-generated objs without defined materials for me to test? I'd like to try a few "real world" files.

**Comment by justinclift** [comment]
Good idea @quillaja, but I don't have them handy any more. :man_shrugging:

Switched focus and set up a completely new dev workstation.  None of the stuff from previous projects on it.

**Comment by quillaja** [comment]
@danaugrs I noticed that although the obj parser will parse the `mtllib` line, it doesn't use it to source the material file, instead always attempting to use the parameter to `Decode()` or `<obj_filename>.mtl` as a backup. As part of the changes I'm making to the decoder for this issue, I'd like to check the file listed in `mtllib` if given. The question is of which takes precedence: mtllib, Decode()'s param, or <obj_filename>.mtl?  

My gut says param, mtllib, then <obj_filename>.mtl as a last ditch attempt. This would allow the user to override the mtllib if they wished by passing in an alternative.

What do you think?

**Comment by danaugrs** [comment]
@quillaja Hey, great questions - I think the Decode()/DecodeReader() param should take precedence if provided. If it's not provided (most common case) then we check `mtllib` and if that fails, then try `<obj_filename>.mtl` as a backup like you proposed. Thanks for working on this!

**Comment by quillaja** [comment]
Of course. I don't often get to contribute to projects, so it's fun to do so when I can.

**Comment by quillaja** [comment]
@danaugrs Pull request(s) sent. I'm headed out on vacation the rest of the week. Let me know at your convenience if you want me to make any revisions. The PR for 'issue 29a' is a separate error I encountered while working on the materials, so I felt it might warrant its own PR. It includes the changes from 'issue 29'. I hope that makes sense. =)

**Comment by danaugrs** [comment]
@quillaja Great, just tested and merged both. Thanks! 😄
