### ISSUE TITLE
Transparency / Rendering order

### ISSUE THREAD

**Issue by t-geindre** [g3n/engine#297]
Hello!
I'm trying to implement a Minecraft like game.
In this game, flowers are rendered like this:
![image](https://github.com/g3n/engine/assets/6348039/e48de3fc-5a20-46d7-bba3-a3ea89eb4665)

I tried to get the same rendering using four vertical plan mesh, centered on the same point and with a 90° rotation between each.
Example: https://gist.github.com/t-geindre/07e2d78574157045c3a6e91cb95920d6

But the issue is that on some view angle, those plans are visible:
![dandelion](https://github.com/g3n/engine/assets/6348039/72b828f1-9dd6-4be4-9eaa-02d33e3d611f)

I'm sure the issue here is the rendering order. But I've no idea how to solve this.

I also tried to create a custom geometry to have those crossed plan in a single mesh.
But, since the geometry type properties are not accessible, I think it's not possible.

Any help would be very appreciated.
And thank you for the work done on this project, I love it!

**Comment by danaugrs** [comment]
Hi! Thanks for the kind words!
You might be able to solve this by disabling the `depthMask` on the flower material:

```go
myFlowerMaterial.SetDepthMask(false)
```

With the depth mask disabled, when the flower planes are rasterized they won't write to the depth buffer, so and the occlusion artifact should disappear. However, this will probably lead to another problem where a plane is visible through the other. You may have to draw four planes instead of two (and keep the `depthMask` on).

Also - please consider joining our Discord if you haven't already: https://discord.gg/NfaeVr8zDg. Would love to see more screenshots of your game.

**Comment by t-geindre** [comment]
Thank you for your quick answer.

It kind of solve my issue. But, as you guessed, I can now see flowers through flowers on some angles:
![floxwer](https://github.com/g3n/engine/assets/6348039/e99b8a54-2e9c-4327-9d66-c20eb3bb48b8)
(sorry for poor quality, but I had to deal with Github file size limitation)

So more plans it is, and split the texture I guess, to apply half of it on each plan.

This game is at a very early stage, and I'm sure you know how side projects go.
But I'll definitely join the Discord server at some point.
