### ISSUE TITLE
[enhancement] Consider adding userdata to Application

### ISSUE THREAD

**Issue by chriscamacho** [g3n/engine#43]
rather than the end user embedding an Application in their own struct, it would probably simpler and more accessible to the novice user, to be able to simply add their own blob of info to the Application structure. (similar to Node's userdata)

**Comment by chriscamacho** [comment]
ended up experimenting with it and it seems to work well

please see https://github.com/g3n/engine/pull/44

**Comment by danaugrs** [comment]
Hi Chris - thanks for the suggestion.

However I don't think this is a good pattern in this case. Usually we want to avoid having empty interfaces as much as possible to allow for type checking. In the case of Node the user-data pattern is necessary because nodes live in a hierarchy and often times users need to access node-related data while traversing the hierarchy. The only two ways to do that in the Node case are:

1. Automatically set a unique ID on each Node and allow users to read that id. That implies that users keep track of a map somewhere which associates data to node ids. Users then need to update the map every time they add a node that they want to track and they need to do map lookups when traversing the hierarchy.
2. The user-data pattern with an empty interface.

In the Node case the user-data pattern allows the engine to not have to worry about unique ids and it removes the burden on the user of needing a map, having to populate it bit by bit, and issuing map lookups when traversing the node hierarchy. It's a beneficial trade-off.

In the Application case, the user-data pattern simply prevents users from having to create their own MyApplication struct which they should be doing in almost every single case, and they lose type-checking in the process.

The below pattern is the recommended one:

```
type MyApplication struct {
    application.Application // Embedded Application
    myTypeCheckedInt        int
    myTypeCheckedString     string
    ...
}
```

I'm planning to write some tutorials to explain the recommended patterns and make it easier on new users!

Thanks!

**Comment by chriscamacho** [comment]
If you embed the Application then there is no way you can get to the MyApplication  when given an Application reference for example in a callback.

At least I'm assuming there's no way to cast an Application into a MyApplication...

**Comment by danaugrs** [comment]
There's no way to obtain the MyApplication instance from the embedded Application instance but you never need to do that. Callbacks should generally have a *MyApplication receiver and thus have access to the MyApplication instance.

**Comment by chriscamacho** [comment]
Its not obvious from the g3nd whats going on with the callbacks other than calling another function inside and anonymous function... but I'm not sure that this is what you mean?

**Comment by chriscamacho** [comment]
never mind... it just dawned on me what you mean, its actually just as easy that way...
