### ISSUE TITLE
SetPaddings doesn't work on Buttons

### ISSUE THREAD

**Issue by amyadzuki** [g3n/engine#75]
It compiles yet seems to have no effect whatsoever.

**Comment by danaugrs** [comment]
I think the problem is that SetPaddings only changes the immediate padding values. However once you hover the cursor over the button or do anything to change its state, a style will be re-applied and the paddings will return to their original values. I'm thinking about how to allow `SetPaddings` and family to work alongside styles...

**Comment by amyadzuki** [comment]
Ohhh ok I can just use styles then personally.  Styles take a bit longer since you have to style the whole thing but you get more control that way.  I'll leave this issue open in case you want to keep it around to track work on `SetPaddings` or something but feel free to close it if you don't need it.
